model_params:
  name: 'GP-CGAN28'
  img_shape: !!python/tuple [1, 28, 28]
  embedd_dim: 50
  latent_dim: 100
  batch_size: 32
  learning_rate: 0.0001
  num_classes: 10
  features_g : 16
  features_d: 16
  input_img_shape: !!python/tuple [1,7,7]


trainer_params:
  gpus: 1
  max_epochs: 50
  log_every_n_steps: 20
  #fast_dev_run: True

logging_params:
  save_dir: "lightning_logs/"
  name: "GP-CGAN28"
  manual_seed: 1265